name: 'Nutrition Framework'
description: 'Final Project for Bachelor Degree, Full and Clear Documentation, Have Empty View :books:'
author: 'Muhammad Faisal Amir'
branding:
  icon: archive
  color: green
inputs:
  myInput:
    description: 'Input to use'
    required: false
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}